cosmetics/cospj/cospj/urls.py
from django.contrib import admin
from django.urls import path, include

import cosapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', cosapp.views.home, name='home'),
    path('users/', include("users.urls")),
    path('review/<int:id>', cosapp.views.addReview, name='review'),
    path('deletereview/<int:product_id>/<int:userreview_id>',
         cosapp.views.deleteReview, name='delete_review'),
    path('editreview/<int:product_id>/<int:userreview_id>',
         cosapp.views.editReview, name='edit_review'),
    path('addproduct/', cosapp.views.addProduct, name='add_product'),
    path('editproduct/<int:id>', cosapp.views.editProduct, name='edit_product'),
    path('deleteproduct/<int:id>',
         cosapp.views.deleteProduct, name='delete_product'),
    path('productdetail/<int:id>', cosapp.views.productDetail, name='productdetail'),
    path('productdetail/<str:name>',
         cosapp.views.productdetail_name, name='productdetail-name'),
    path('producttype/<int:id>', cosapp.views.productType, name='producttype'),
    path('search_products', cosapp.views.search_products, name="search-products"),
    path('list_types', cosapp.views.list_types, name='list-types'),
    path('show_type/<type_id>', cosapp.views.show_type, name='show-type'),
    path('update_profile/', cosapp.views.update_profile, name='update-profile'),
    path('productlist/', cosapp.views.product_list, name='productlist'),
]

cosmetics/cospj/users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login", views.login_view, name = "login"),
    path("logout", views.logout_view, name = "logout"),
    path("signup", views.signup_view, name = "signup"),
]

cosmetics/cospj/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin


# Create your models here.
class User(AbstractUser, PermissionsMixin):
    nickname = models.CharField(max_length=30)
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    skin_type = models.CharField(max_length=30)
    address = models.CharField(max_length=50)

cosmetics/cospj/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import redirect
from .models import User
import mysql.connector

# Create your views here.

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username = username, password = password)
        if user is not None:
            messages.success(request, "Logged in successfully!")
            print("Logged successfully")
            login(request, user)
        else:
            messages.warning(request, "Invalid username or password!")
            print("Login failed")
        
    return render(request, "home.html")

def logout_view(request):
    logout(request)
    
    return redirect("home")

def signup_view(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        nickname = request.POST["nickname"]
        age = request.POST["age"]
        gender = request.POST["gender"]
        skin_type = request.POST["skin_type"]
        address = request.POST["address"]
        email = request.POST["email"]
        is_superuser = request.POST["is_superuser"]
        is_staff = request.POST["is_staff"]

        cnx = mysql.connector.connect(
            host = 'localhost',
            user = 'root',
            password = '0000',
            database = 'cosmetics'
        )

        cursor = cnx.cursor()
        query = "SELECT check_username(%s)"
        cursor.execute(query, (username,))
        exist = cursor.fetchone()[0]

        print("***** exist: ", exist)
        cursor.close()
        cnx.close()

        if exist != 0:
            messages.warning(request, "username already exists!")
            print("Sign up failed")
            return render(request, "users/signup.html")
        
        user = User.objects.create_user(
            username = username,
            email = email,
            password = password,
            nickname = nickname,
            age = age,
            gender = gender,
            skin_type = skin_type,
            address = address,
            is_superuser = is_superuser,
            is_staff = is_staff,
        )
        user.save()
        return redirect("user:login")
        
    return render(request, "users/signup.html")

cosmetics/cospj/users/templates/users/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %} Login {% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        <h4>Welcome {{ user.username }}</h4>
        <a href = "{% url "user:logout" %}"> logout </a>
    {% else %}
        <form action = "{% url "user:login" %}" method = "POST">
            {% csrf_token %}
            <input name = "username" type = "text" placeholder = "username"></br>
            <input name = "password" type = "password" placeholder = "password"></br>
            <input type = "submit" value = "login"></br>
        </form>

        <a href = "{% url "user:signup" %}"> Sign up </a>
    {% endif %}

{% endblock %}

cosmetics/cospj/users/templates/users/signup.html
Sign up page
<br>

{% block content %}

    {% if messages %}
    <ul class = "messages">
        {% for message in messages %}
            {% if forloop.last %}
                <li {% if message.tags %} class = "{{ message.tags}}" {% endif %}> {{ message }}</li>
            {% endif %}
        {% endfor %}
    </ul>
    {% endif %}


    <form action = "" method = "POST">
        {% csrf_token %}
        <p> username </p>
        <input name = "username" type = "text">
        <p> password </p>
        <input name = "password" type = "password">
        <p> email </p>
        <input name = "email" type = "text">
        <p> nickname </p>
        <input name = "nickname" type = "text">
        <p> age </p>
        <input name = "age" type = "text">
        <p> gender </p>
        <input name = "gender" type = "text">
        <p> skin_type </p>
        <input name = "skin_type" type = "text">
        <p> address </p>
        <input name = "address" type = "text">
        <p> If company admin, enter 1. Otherwise, enter 0 </p>
        <input name = "is_superuser" type = "number">
        <p> If expert, enter 1. Otherwise, enter 0 </p>
        <input name = "is_staff" type = "number"></br></br>
        <input type = "submit" value = "sign up">
    </form>

{% endblock %}